b
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>

diff --git a/.github/workflows/pr-for-updates.yaml b/.github/workflows/pr-for-updates.yaml
--- a/.github/workflows/pr-for-updates.yaml
+++ b/.github/workflows/pr-for-updates.yaml
@@ -15,12 +15,30 @@ jobs:
       - uses: actions/checkout@v2
       - name: Create a Pull Request
         run: |
+          branches1=$(git branch)
+          echo $branches1
+          branches=$(git branch -r --list "fork/update/*")
           ref=${{ github.ref }}
           branch=${ref#"refs/heads/"}
 
           prTitle="Update from $branch"
           prBody=$(git log --pretty='format:%B' -1 | sed '/^$/d;$d' | sed 's/#/# /g')
 
-          gh pr create -B "main" -H "$ref" --title "$prTitle" --body "$prBody"
+          timeout_sec=120
+          t0=$(date '+%s')
+          remaining=$(expr ${timeout_sec} + ${t0} - "$(date '+%s')")
+          while [[ ${remaining} -gt 0 ]]
+          do
+              echo "Starting command..."
+              if gh pr create -B "main" -H "$ref" --title "$prTitle" --body "$prBody" ; then
+                exit 0
+              else
+                sleep 30
+              fi
+              echo "Command has failed. Retry"
+              remaining=$(expr ${timeout_sec} + ${t0} - "$(date '+%s')")
+          done
+
+          exit 1
         env:
           GITHUB_TOKEN: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
