test
Signed-off-by: NikitaSkrynnik <nikita.skrynnik@xored.com>

diff --git a/.github/workflows/update-refs.yaml b/.github/workflows/update-refs.yaml
--- a/.github/workflows/update-refs.yaml
+++ b/.github/workflows/update-refs.yaml
@@ -15,6 +15,7 @@ jobs:
         with:
           fetch-depth: 0
       - name: Update references
+        shell: bash {0} # Makes script continue execution even if some commands return non-zero exit code
         run: |
           git config --global user.email "nsmbot@networkservicmesh.io"
           git config --global user.name "nsmbot"
@@ -24,3 +25,5 @@ jobs:
           git add -- .
           git commit -s -m "remove to ref"
           git push origin test
+
+          echo "Exit code: $?"
